### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by james-powis** [kontron/robotframework-snmplibrary#15] opened 2019-02-19 20:29 UTC
With python 2 being less than a year from End of Life, we are not in the process of evaluating and upgrading code to python3 where possible. 

As this is one of our dependencies, and I see someone has done some of the python3 leg work, can we please get a release cut for this library?

**Comment by hthiery** [comment] 2019-02-21 07:57
just released v0.2 with python 3 support ... please check if this works for you and give feedback

**Comment by vladwoguer** [comment] 2019-02-21 19:31
When I try:
pip3 install robotframework-snmplibrary==0.2.0

I'm getting the following error:
Collecting robotframework-snmplibrary==0.2.0
  Using cached https://files.pythonhosted.org/packages/ac/f2/eddde2d912f0fc8b87decd94bfc3436701397dc67e3ac64d387d142b8ad0/robotframework-snmplibrary-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-xaess3d3/robotframework-snmplibrary/setup.py", line 14, in <module>
        stderr=subprocess.STDOUT).rstrip().decode('ascii')
      File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--always', '--dirty']' returned non-zero exit status 128.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xaess3d3/robotframework-snmplibrary/setup.py", line 22, in <module>
        exec(f, d)
    TypeError: exec() arg 1 must be a string, bytes or code object

**Comment by hthiery** [comment] 2019-03-04 12:20
just released a new version .. please check if the issue is fixed now

**Closed** 2023-01-05 14:25 UTC
